apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.postgresql.secret.secretkey | b64enc }}