apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    release: {{ .Release.Name }}
type: Opaque
data:
  DB_USER: {{ .Values.postgresql.secret.dbuser | b64enc }}
  DB_PASSWORD: {{ .Values.postgresql.secret.dbpassword | b64enc }}
  DB_HOST: {{ .Values.postgresql.secret.dbhost | b64enc }} 
  DB_PORT: {{ .Values.postgresql.secret.dbport | b64enc }} 
  DB_NAME: {{ .Values.postgresql.secret.database | b64enc }} 
  SECRET_KEY: {{ .Values.postgresql.secret.secretkey | b64enc }}