apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    release: {{ .Release.Name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.secret.dbuser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.secret.dbpassword | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.secret.database | b64enc }}